### ISSUE TITLE
libretime-liquidsoap (exit status 1; not expected)

### ISSUE THREAD

**Issue by maydo** [ned-kelly/docker-multicontainer-libretime#24]
>2019-03-16 14:05:32,271 INFO spawned: 'libretime-liquidsoap' with pid 158
2019-03-16 14:05:34,130 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-16 14:06:03,502 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2019-03-16 14:06:04,507 INFO spawned: 'libretime-liquidsoap' with pid 159
2019-03-16 14:06:06,253 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-16 14:06:35,789 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2019-03-16 14:06:36,455 INFO spawned: 'libretime-liquidsoap' with pid 175
2019-03-16 14:06:38,219 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-16 14:07:07,589 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2019-03-16 14:07:08,594 INFO spawned: 'libretime-liquidsoap' with pid 176
2019-03-16 14:07:10,408 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-16 14:07:39,776 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2019-03-16 14:07:40,780 INFO spawned: 'libretime-liquidsoap' with pid 178
2019-03-16 14:07:41,869 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-16 14:08:12,018 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2019-03-16 14:08:12,050 INFO spawned: 'libretime-liquidsoap' with pid 179
2019-03-16 14:08:13,956 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-16 14:08:43,335 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2019-03-16 14:08:44,339 INFO spawned: 'libretime-liquidsoap' with pid 196
2019-03-16 14:08:46,087 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-16 14:09:15,468 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2019-03-16 14:09:16,472 INFO spawned: 'libretime-liquidsoap' with pid 239
2019-03-16 14:09:18,470 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

i cannot access lanip:8882 (oops, something wrong)
see logs from libretime-core
i run always into liquidsoap issues :)

**Comment by maydo** [comment]
>
HTTP Error 500: Internal Server Error
traceback: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airtime_playout-1.0-py2.7.egg/liquidsoap/generate_liquidsoap_cfg.py", line 48, in run
    ss = ac.get_stream_setting()
  File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py", line 470, in get_stream_setting
    return self.services.get_stream_setting()
  File "/usr/local/lib/python2.7/dist-packages/api_clients-1.0-py2.7.egg/api_clients/api_client.py", line 145, in __call__
    f = urllib2.urlopen(req, timeout=ApiRequest.API_HTTP_REQUEST_TIMEOUT)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error

this is from inside container
/var/log/supervisor/libretime-liquidsoap-stderr---supervisor-wE8Q2h.log

from apache logs

172.18.0.2:80 127.0.0.1 - - [16/Mar/2019:17:44:17 +0000] "GET /api/get-stream-setting/format/json/api_key/xxxxx/ HTTP/1.1" 500 874 "-" "Python-urllib/2.7"
172.18.0.2:80 127.0.0.1 - - [16/Mar/2019:17:44:17 +0000] "GET /api/version/api_key/xxxxxHTTP/1.1" 500 874 "-" "Python-urllib/2.7"
172.18.0.2:80 127.0.0.1 - - [16/Mar/2019:17:44:20 +0000] "GET /api/get-stream-setting/format/json/api_key/xxxxx/ HTTP/1.1" 500 874 "-" "Python-urllib/2.7"
172.18.0.2:80 127.0.0.1 - - [16/Mar/2019:17:44:22 +0000] "GET /api/version/api_key/xxxxxHTTP/1.1" 500 874 "-" "Python-urllib/2.7"
172.18.0.2:80 127.0.0.1 - - [16/Mar/2019:17:44:23 +0000] "GET /api/get-stream-setting/format/json/api_key/xxxxx/ HTTP/1.1" 500 874 "-" "Python-urllib/2.7"
172.18.0.2:80 127.0.0.1 - - [16/Mar/2019:17:44:26 +0000] "GET /api/get-stream-setting/format/json/api_key/xxxxx/ HTTP/1.1" 500 874 "-" "Python-urllib/2.7"
172.18.0.2:80 127.0.0.1 - - [16/Mar/2019:17:44:27 +0000] "GET /api/version/api_key/xxxxx/ HTTP/1.1" 500 874 "-" "Python-urllib/2.7"

>tail -f /var/log/supervisor/libretime-liquidsoap-stdout---supervisor-syOqSy.log 
Unable to connect to the Airtime server.
Unable to connect to the Airtime server.

**Comment by maydo** [comment]
got it fixed

/opt/libretime/libretime-core/config/airtime/airtime.conf
&& liquidsoap.cfg
was not created on first pull
deleted the folder and repulled the image
its working now

**Comment by engineerjoe440** [comment]
Looks like I'm running into the same sort of issue...

```
sudo docker logs -f libretime-core
Prepping libretime for first run...
 * Restarting Apache httpd web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
   ...done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   324  100   240  100    84    236     82  0:00:01  0:00:01 --:--:--   236
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   288  100   184  100   104    728    411 --:--:-- --:--:-- --:--:--   730
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    76  100    28  100    48    964   1652 --:--:-- --:--:-- --:--:--  1714
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   105  100    42    633    253 --:--:-- --:--:-- --:--:--   636
{"message":"Couldn't establish a connection to the database! Please check your credentials and try again. PDO Exception: SQLSTATE[08006] [7] FATAL:  password authentication failed for user \"joestan\"","errors":["dbName","dbUser","dbPass"]}{"message":"Couldn't connect to RabbitMQ server! Please check if the server is running and your credentials are correct.","errors":["rmqUser","rmqPass","rmqHost","rmqPort","rmqVHost"]}{"message":null,"errors":[]}{"message":"Failed to insert media folder; database isn't configured properly!","errors":["mediaFolder"]}Enabling module substitute.
To activate the new configuration, you need to run:
  service apache2 restart
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2020-11-25 03:51:17,424 CRIT Supervisor running as root (no user in config file)
2020-11-25 03:51:17,436 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2020-11-25 03:51:18,681 INFO RPC interface 'supervisor' initialized
2020-11-25 03:51:18,682 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-11-25 03:51:18,682 INFO supervisord started with pid 79
2020-11-25 03:51:19,703 INFO spawned: 'icecast-tcp-proxy' with pid 82
2020-11-25 03:51:19,707 INFO spawned: 'rabbitmq-tcp-proxy' with pid 83
2020-11-25 03:51:19,711 INFO spawned: 'postgres-tcp-proxy' with pid 84
2020-11-25 03:51:19,723 INFO spawned: 'apache2' with pid 85
2020-11-25 03:51:19,731 INFO spawned: 'libretime-playout' with pid 86
2020-11-25 03:51:19,735 INFO spawned: 'libretime-liquidsoap' with pid 87
2020-11-25 03:51:19,739 INFO spawned: 'libretime-celery' with pid 88
2020-11-25 03:51:19,745 INFO spawned: 'libretime-airtime_analyzer' with pid 89
2020-11-25 03:51:19,754 INFO spawned: 'cron' with pid 90
2020-11-25 03:51:20,756 INFO success: icecast-tcp-proxy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:51:20,793 INFO success: rabbitmq-tcp-proxy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:51:20,793 INFO success: postgres-tcp-proxy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:51:20,794 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:51:20,794 INFO success: libretime-playout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:51:20,794 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:51:20,794 INFO success: libretime-celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:51:20,794 INFO success: libretime-airtime_analyzer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:51:20,794 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:51:37,803 INFO exited: apache2 (exit status 0; expected)
2020-11-25 03:52:05,382 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2020-11-25 03:52:06,389 INFO spawned: 'libretime-liquidsoap' with pid 175
2020-11-25 03:52:08,208 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:52:37,540 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2020-11-25 03:52:38,546 INFO spawned: 'libretime-liquidsoap' with pid 176
2020-11-25 03:52:40,285 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:53:09,606 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2020-11-25 03:53:10,533 INFO spawned: 'libretime-liquidsoap' with pid 177
2020-11-25 03:53:12,235 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:53:41,574 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2020-11-25 03:53:42,580 INFO spawned: 'libretime-liquidsoap' with pid 178
2020-11-25 03:53:44,288 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:54:13,646 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2020-11-25 03:54:14,652 INFO spawned: 'libretime-liquidsoap' with pid 196
2020-11-25 03:54:15,868 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:54:45,692 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2020-11-25 03:54:46,032 INFO spawned: 'libretime-liquidsoap' with pid 197
2020-11-25 03:54:47,735 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:55:17,060 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2020-11-25 03:55:18,064 INFO spawned: 'libretime-liquidsoap' with pid 201
2020-11-25 03:55:19,768 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-25 03:55:49,139 INFO exited: libretime-liquidsoap (exit status 1; not expected)
2020-11-25 03:55:50,144 INFO spawned: 'libretime-liquidsoap' with pid 202
2020-11-25 03:55:51,381 INFO success: libretime-liquidsoap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
^C
```

I've also verified that the `/opt/libretime/libretime-core/config/airtime/airtime.conf` file does not exist (and the liquidsoap.cfg also appears missing, but I wasn't sure which path that file should appear in).

```
/opt/libretime$ ls libretime-core/
bootstrap  config  customisations  Dockerfile
```

@maydo Did you just re-pull the `libretime-core` container? Or did you start the whole installation process (as specified on the README) over again?

Still a bit of a container noob here, so I might need just a little prodding in the right direction.

**Comment by engineerjoe440** [comment]
Realized that my terminal capture (after running `sudo docker pull bushrangers/ubuntu-multicontainer-libretime:libretime-latest`) the config folder showed up... tried restarting the container, and still no luck. Any additional thoughts? I did also capture this screenshot of the /?config help page:
![image](https://user-images.githubusercontent.com/33275230/100300919-e40c5c00-2f4b-11eb-99aa-d97572a7ac75.png)

**Comment by engineerjoe440** [comment]
Okay.... I mucked around some more and got it working (I think....).

I deleted the `/opt/libretime/libretime-core/` folder, and then ran `sudo docker-compose up -d` again... magically started working...
